"""add class teacher

Revision ID: dbc99fe5f0e4
Revises: df040e090a05
Create Date: 2026-03-28 23:16:04.232543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc99fe5f0e4'
down_revision: Union[str, Sequence[str], None] = 'df040e090a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classrooms', sa.Column('class_teacher', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classrooms', 'class_teacher')
    # ### end Alembic commands ###
